# Generated by Django 4.1.7 on 2024-06-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('sku', models.CharField(blank=True, max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('JO', 'Joyería de autor'), ('CA', 'Carteras'), ('VE', 'Vestimenta'), ('CZ', 'Calzado')], max_length=2)),
                ('imagen_producto', models.ImageField(upload_to='product')),
            ],
        ),
    ]
