# Generated by Django 4.1.7 on 2024-06-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
