# Generated by Django 5.0.6 on 2024-06-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
