# Generated by Django 5.0.6 on 2024-06-16 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_cliente_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('cvv', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
