# Generated by Django 5.0.6 on 2024-06-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_tcredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
