# Generated by Django 5.0.6 on 2024-06-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_orderplaced_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='envio',
            field=models.IntegerField(default=5000),
        ),
    ]
