# Generated by Django 5.0.6 on 2024-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_orderplaced_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tipopago',
            field=models.CharField(default='', max_length=100),
        ),
    ]
